
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: festivo
      MYSQL_USER: festivo
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
